[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
    [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
